// @ll-compat-audit: ok 2026-08-01

export const EMAIL_EXPIRATION_NOTIFICATION_QUEUE = 'EMAIL_EXPIRATION_NOTIFICATION_QUEUE';

export const WEEK_BEFORE_NOTIFICATION = 'WEEK_BEFORE_NOTIFICATION';
export const EXPIRATION_NOTIFICATION = 'EXPIRATION_NOTIFICATION';
