/**
 * Durable auth scope strings. Keep values identical to lib/constants/scopes.
 */
export {
  ALL,
  SITE_ADMIN,
  SITE_CAN_CREATE_ORG,
  OBSERVER,
  XAPI_ALL,
  XAPI_READ,
  XAPI_STATEMENTS_READ,
  XAPI_STATEMENTS_WRITE,
  XAPI_STATEMENTS_READ_MINE,
  XAPI_STATE_ALL,
  XAPI_PROFILE_ALL,
  XAPI_STATEMENTS_DELETE,
  XAPI_SCOPES,
  API_SCOPES,
  CLIENT_SCOPES,
  SITE_SCOPES,
  USER_SCOPES,
  VIEW_SHAREABLE_DASHBOARD,
} from 'lib/constants/scopes';
